# Generated by Django 2.2.4 on 2019-08-10 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0002_auto_20190810_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='nbr_rooms_available',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
    ]
