# Generated by Django 2.2.4 on 2019-08-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_timeslot_nbr_rooms_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='identif',
            field=models.CharField(choices=[('TR08000920', 'TR 8:00 - 9:20'), ('TR09301050', 'TR 9:30 - 10:50'), ('TR11001220', 'TR 11:00 - 12:20'), ('TR12301350', 'TR 12:30 - 13:50'), ('TR14001520', 'TR 14:00 - 15:20'), ('TR15301650', 'TR 15:30 - 16:50'), ('TR17001820', 'TR 17:00 - 18:20'), ('TR18301950', 'TR 18:30 - 19:50'), ('MWF08000850', 'MWF 8:00 - 8:50'), ('MWF09000950', 'MWF 9:00 - 9:50'), ('MWF10001050', 'MWF 10:00 - 10:50'), ('MWF11001150', 'MWF 11:00 - 11:50'), ('MWF12001250', 'MWF 12:00 - 12:50'), ('MWF13401430', 'MWF 13:40 - 14:30'), ('MW12001320', 'MW 12:00 - 13:20'), ('MW15401700', 'MW 15:40 - 17:00'), ('MW17101830', 'MW 17:10 - 18:30')], max_length=12),
        ),
    ]
